import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { GeneratePlanButton } from '@/components/plan/GeneratePlanButton'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { format, parseISO } from 'date-fns'

export default async function PlanPage() {
  const supabase = await createClient()
  const { data: { session } } = await supabase.auth.getSession()

  if (!session?.user) {
    redirect('/login')
  }

  // Fetch the latest active plan
  const { data: plans, error } = await supabase
    .from('training_plans')
    .select('*')
    .eq('user_id', session.user.id)
    .order('created_at', { ascending: false })
    .limit(1)

  const activePlan = plans?.[0]

  return (
    <div className="min-h-screen bg-gray-50 p-4 sm:p-8">
      <div className="max-w-4xl mx-auto space-y-8">
        <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Training Plan</h1>
            <p className="text-gray-500 mt-2">Your AI-generated schedule to hit your goals.</p>
          </div>
          <GeneratePlanButton />
        </header>

        <section>
          {!activePlan ? (
            <div className="p-12 text-center bg-white border rounded-xl text-gray-500 shadow-sm">
              <p>You don't have an active training plan yet.</p>
              <p className="text-sm mt-2">Set a goal and click the button above to generate one.</p>
            </div>
          ) : (
            <div className="space-y-6">
              <div className="text-sm font-medium text-gray-500 uppercase tracking-wide">
                Valid from {format(parseISO(activePlan.valid_from), 'MMM d')} to {activePlan.valid_until ? format(parseISO(activePlan.valid_until), 'MMM d') : 'Open-ended'}
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {Object.entries(activePlan.plan as Record<string, string>).map(([day, description]) => (
                  <Card key={day} className="bg-white">
                    <CardHeader className="pb-2">
                      <CardTitle className="text-lg">{day}</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <p className="text-gray-700 leading-relaxed">{description}</p>
                    </CardContent>
                  </Card>
                ))}
              </div>
              
              <div className="text-xs text-right text-gray-400">
                Generated by {activePlan.generated_by}
              </div>
            </div>
          )}
        </section>
      </div>
    </div>
  )
}
